#!/usr/bin/env node
// CodeMie Statusline - auto-generated by codemie-claude --status
// Shows: [Model] dir | branch / context bar % | $cost | duration
//
// NOTE: This file is deployed as a standalone script to ~/.claude/ and has no
// access to the CodeMie utils layer. Direct child_process and path imports are
// intentional here - this script runs independently without the project runtime.
/* eslint-disable */
import { execSync } from 'child_process';
import { basename } from 'path';

let input = '';
process.stdin.on('data', chunk => input += chunk);
process.stdin.on('end', () => {
  try {
    const data = JSON.parse(input);
    const model = data.model?.display_name || 'Claude';
    const dir = basename(data.workspace?.current_dir || process.cwd());
    const cost = data.cost?.total_cost_usd || 0;
    const pct = Math.floor(data.context_window?.used_percentage || 0);
    const durationMs = data.cost?.total_duration_ms || 0;

    const CYAN = '\x1b[36m', GREEN = '\x1b[32m', YELLOW = '\x1b[33m', RED = '\x1b[31m', RESET = '\x1b[0m';

    const barColor = pct >= 90 ? RED : pct >= 70 ? YELLOW : GREEN;
    const filled = Math.floor(pct / 10);
    const bar = '█'.repeat(filled) + '░'.repeat(10 - filled);

    const mins = Math.floor(durationMs / 60000);
    const secs = Math.floor((durationMs % 60000) / 1000);

    let branch = '';
    try {
      branch = execSync('git branch --show-current', { encoding: 'utf8', stdio: ['pipe', 'pipe', 'ignore'] }).trim();
      branch = branch ? ' | 🌿 ' + branch : '';
    } catch {}

    process.stdout.write(CYAN + '[' + model + ']' + RESET + ' 📁 ' + dir + branch + '\n');
    process.stdout.write(barColor + bar + RESET + ' ' + pct + '% | ' + YELLOW + '$' + cost.toFixed(4) + RESET + ' | ⏱️ ' + mins + 'm ' + secs + 's\n');
  } catch {
    // Silent fail - statusline must never crash Claude Code
  }
});
